[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@ds-test/=lib/ds-test/src/",
    "@solmate/=lib/solmate/src/",
    "@forge-std/=lib/forge-std/src/",
    "@oz/=lib/oz/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@zondax/filecoin-solidity/=node_modules/@zondax/filecoin-solidity/",
    "@ensdomains/buffer/contracts/=node_modules/@ensdomains/buffer/contracts/",
    
    "solidity-cborutils/=node_modules/solidity-cborutils/",
]

rpc_endpoints = { calibration = '${CALIBRATION}' }
chain_id = 3141
fuzz_runs = 256
optimizer = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
